'use strict'

const { test } = require('node:test')
const {
  webtransportCodeToHttpCode,
  httpCodeToWebtransportCode,
  computeCertificateHash,
  verifyCertificateHash,
  encodeVarint,
  decodeVarint
} = require('../../lib/web/webtransport/util')
const {
  wtApplicationErrorFirst,
  wtApplicationErrorLast
} = require('../../lib/web/webtransport/constants')

test('WebTransport <-> HTTP/3 error code mapping', async (t) => {
  await t.test('matches the endpoints defined by draft-ietf-webtrans-http3', (t) => {
    // "0x00000000 corresponds to 0x52e4a40fa8db, and 0xffffffff
    //  corresponds to 0x52e5ac983162"
    t.assert.strictEqual(webtransportCodeToHttpCode(0), wtApplicationErrorFirst)
    t.assert.strictEqual(webtransportCodeToHttpCode(0xffffffff), wtApplicationErrorLast)
  })

  await t.test('skips codepoints reserved by HTTP/3', (t) => {
    for (let n = 0; n < 0x100; n++) {
      const h = webtransportCodeToHttpCode(n)
      // "there are codepoints inside that range of form "0x1f * N + 0x21"
      //  that are reserved ... those have to be skipped"
      t.assert.notStrictEqual((h - 0x21n) % 0x1fn, 0n, `code ${n} mapped onto a reserved codepoint`)
    }
  })

  await t.test('round-trips', (t) => {
    for (const n of [0, 1, 0x1d, 0x1e, 0x1f, 100, 0x1000, 0xfffffffe, 0xffffffff]) {
      t.assert.strictEqual(httpCodeToWebtransportCode(webtransportCodeToHttpCode(n)), n)
    }
  })

  await t.test('returns null outside the WT_APPLICATION_ERROR range and for reserved codepoints', (t) => {
    t.assert.strictEqual(httpCodeToWebtransportCode(0x100n), null)
    t.assert.strictEqual(httpCodeToWebtransportCode(wtApplicationErrorLast + 1n), null)
    let reserved = wtApplicationErrorFirst
    while ((reserved - 0x21n) % 0x1fn !== 0n) reserved++
    t.assert.strictEqual(httpCodeToWebtransportCode(reserved), null)
  })
})

test('QUIC variable-length integers', async (t) => {
  await t.test('encodes the RFC 9000 Appendix A examples', (t) => {
    t.assert.strictEqual(Buffer.from(encodeVarint(37n)).toString('hex'), '25')
    t.assert.strictEqual(Buffer.from(encodeVarint(15293n)).toString('hex'), '7bbd')
    t.assert.strictEqual(Buffer.from(encodeVarint(494878333n)).toString('hex'), '9d7f3e7d')
    t.assert.strictEqual(Buffer.from(encodeVarint(151288809941952652n)).toString('hex'), 'c2197c5eff14e88c')
  })

  await t.test('round-trips across boundaries', (t) => {
    for (const value of [0n, 63n, 64n, 16383n, 16384n, 1073741823n, 1073741824n, 4611686018427387903n]) {
      const encoded = encodeVarint(value)
      t.assert.deepStrictEqual(decodeVarint(encoded), { value, length: encoded.length })
    }
  })

  await t.test('rejects values that do not fit', (t) => {
    t.assert.throws(() => encodeVarint(2n ** 62n), RangeError)
  })

  await t.test('returns null for truncated input', (t) => {
    t.assert.strictEqual(decodeVarint(new Uint8Array(0)), null)
    t.assert.strictEqual(decodeVarint(encodeVarint(16384n).slice(0, 2)), null)
  })
})

test('certificate hashes', async (t) => {
  const { X509Certificate } = require('node:crypto')
  // A self-signed certificate is generated by `npm run generate-pem` for
  // the test suite; fall back to a skip when unavailable.
  let cert = null
  try {
    const { readFileSync } = require('node:fs')
    const { join } = require('node:path')
    cert = new X509Certificate(readFileSync(join(__dirname, '../fixtures/cert.pem')))
  } catch {}

  await t.test('verify a certificate hash', { skip: cert === null ? 'no test certificate' : false }, (t) => {
    const hash = computeCertificateHash(cert)
    // 2. Compute the SHA-256 hash of cert and return the computed value.
    t.assert.strictEqual(hash.length, 32)

    // 3.1.2. If hashValue is equal to referenceHash, return true.
    t.assert.strictEqual(verifyCertificateHash(cert, [{ algorithm: 'sha-256', value: hash }]), true)
    // hash.algorithm is an ASCII case-insensitive match with "sha-256"
    t.assert.strictEqual(verifyCertificateHash(cert, [{ algorithm: 'SHA-256', value: hash }]), true)
    // The user agent SHALL ignore any hash that uses an unknown algorithm.
    t.assert.strictEqual(verifyCertificateHash(cert, [{ algorithm: 'sha-512', value: hash }]), false)
    // 4. Return false.
    t.assert.strictEqual(verifyCertificateHash(cert, [{ algorithm: 'sha-256', value: new Uint8Array(32) }]), false)
    t.assert.strictEqual(verifyCertificateHash(cert, []), false)
  })
})
